# Generated by Django 5.0.14 on 2026-10-02 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0009_document_owner_node'),
        ('organization', '0005_orgevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonConformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('AUDIT', 'ممیزی'), ('COMPLAINT', 'شکایت'), ('INSPECTION', 'بازرسی'), ('INTERNAL', 'گزارش داخلی'), ('OTHER', 'سایر')], default='INTERNAL', max_length=12)),
                ('severity', models.CharField(choices=[('MINOR', 'جزئی'), ('MAJOR', 'عمده'), ('CRITICAL', 'بحرانی')], default='MINOR', max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'ثبت\u200cشده، منتظر بررسی'), ('IN_PROGRESS', 'در دست اقدام'), ('CLOSED', 'بسته\u200cشده'), ('REJECTED', 'ردشده')], default='OPEN', max_length=12)),
                ('detected_on', models.DateField()),
                ('root_cause', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('effectiveness_note', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nonconformances', to='organization.orgnode')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nonconformances', to='documents.document')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_nonconformances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QualityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('nc_reported', 'عدم\u200cانطباق ثبت شد'), ('nc_edited', 'عدم\u200cانطباق ویرایش شد'), ('nc_accepted', 'عدم\u200cانطباق پذیرفته شد'), ('nc_rejected', 'عدم\u200cانطباق رد شد'), ('nc_closed', 'عدم\u200cانطباق بسته شد'), ('nc_reopened', 'عدم\u200cانطباق بازگشایی شد')], max_length=32)),
                ('actor_name', models.CharField(max_length=255)),
                ('actor_title', models.CharField(blank=True, max_length=255)),
                ('subject_title', models.CharField(blank=True, max_length=255)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(blank=True, max_length=16)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quality.nonconformance')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='nonconformance',
            index=models.Index(fields=['status', 'owner_node'], name='nc_status_node_idx'),
        ),
        migrations.AddIndex(
            model_name='nonconformance',
            index=models.Index(fields=['owner_node', 'created_at'], name='nc_node_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='nonconformance',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'CLOSED'), _negated=True), ('closed_at__isnull', False), _connector='OR'), name='nc_closed_has_closed_at'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['nc', 'created_at'], name='qevent_nc_time_idx'),
        ),
    ]
