# Generated by Django 5.0.14 on 2026-10-02 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityevent',
            name='kind',
            field=models.CharField(choices=[('nc_reported', 'عدم\u200cانطباق ثبت شد'), ('nc_edited', 'عدم\u200cانطباق ویرایش شد'), ('nc_accepted', 'عدم\u200cانطباق پذیرفته شد'), ('nc_rejected', 'عدم\u200cانطباق رد شد'), ('nc_closed', 'عدم\u200cانطباق بسته شد'), ('nc_reopened', 'عدم\u200cانطباق بازگشایی شد'), ('action_added', 'اقدام اصلاحی افزوده شد'), ('action_edited', 'اقدام اصلاحی ویرایش شد'), ('action_assigned', 'اقدام اصلاحی واگذار شد'), ('action_status_changed', 'وضعیت اقدام تغییر کرد'), ('action_due_changed', 'مهلت اقدام تغییر کرد'), ('action_verified', 'اقدام تایید شد'), ('action_verification_failed', 'تایید اقدام ناموفق بود'), ('action_cancelled', 'اقدام لغو شد')], max_length=32),
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_on', models.DateField()),
                ('status', models.CharField(choices=[('TODO', 'انجام نشده'), ('IN_PROGRESS', 'در حال انجام'), ('DONE', 'انجام شد، منتظر تایید'), ('VERIFIED', 'تایید شد'), ('CANCELLED', 'لغو شد')], default='TODO', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_note', models.TextField(blank=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('nc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='quality.nonconformance')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_on', 'id'],
            },
        ),
        migrations.AddField(
            model_name='qualityevent',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='quality.correctiveaction'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['nc', 'status'], name='action_nc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['assignee', 'status'], name='action_assignee_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='correctiveaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'VERIFIED'), _negated=True), ('verified_at__isnull', False), _connector='OR'), name='action_verified_has_verified_at'),
        ),
    ]
