# Generated by Django 5.0.14 on 2026-10-02 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_orgevent'),
        ('quality', '0002_alter_qualityevent_kind_correctiveaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityevent',
            name='kind',
            field=models.CharField(choices=[('nc_reported', 'عدم\u200cانطباق ثبت شد'), ('nc_edited', 'عدم\u200cانطباق ویرایش شد'), ('nc_accepted', 'عدم\u200cانطباق پذیرفته شد'), ('nc_rejected', 'عدم\u200cانطباق رد شد'), ('nc_closed', 'عدم\u200cانطباق بسته شد'), ('nc_reopened', 'عدم\u200cانطباق بازگشایی شد'), ('action_added', 'اقدام اصلاحی افزوده شد'), ('action_edited', 'اقدام اصلاحی ویرایش شد'), ('action_assigned', 'اقدام اصلاحی واگذار شد'), ('action_status_changed', 'وضعیت اقدام تغییر کرد'), ('action_due_changed', 'مهلت اقدام تغییر کرد'), ('action_verified', 'اقدام تایید شد'), ('action_verification_failed', 'تایید اقدام ناموفق بود'), ('action_cancelled', 'اقدام لغو شد'), ('audit_planned', 'ممیزی برنامه\u200cریزی شد'), ('audit_edited', 'ممیزی ویرایش شد'), ('audit_auditor_changed', 'ممیز اصلی تغییر کرد'), ('audit_started', 'ممیزی آغاز شد'), ('audit_completed', 'ممیزی انجام شد'), ('audit_cancelled', 'ممیزی لغو شد'), ('finding_raised', 'یافتهٔ ممیزی ثبت شد')], max_length=32),
        ),
        migrations.CreateModel(
            name='InternalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('planned_on', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'برنامه\u200cریزی\u200cشده'), ('IN_PROGRESS', 'در حال انجام'), ('COMPLETED', 'انجام\u200cشده'), ('CANCELLED', 'لغو شد')], default='PLANNED', max_length=12)),
                ('summary', models.TextField(blank=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lead_auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_audits', to=settings.AUTH_USER_MODEL)),
                ('scope_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='organization.orgnode')),
            ],
            options={
                'ordering': ['-planned_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='quality.internalaudit'),
        ),
        migrations.AddField(
            model_name='qualityevent',
            name='audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quality.internalaudit'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['audit', 'created_at'], name='qevent_audit_time_idx'),
        ),
        migrations.AddIndex(
            model_name='internalaudit',
            index=models.Index(fields=['status', 'scope_node'], name='audit_status_node_idx'),
        ),
        migrations.AddIndex(
            model_name='internalaudit',
            index=models.Index(fields=['lead_auditor', 'status'], name='audit_auditor_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='internalaudit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='audit_completed_has_completed_at'),
        ),
        migrations.AddConstraint(
            model_name='internalaudit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status__in', ['IN_PROGRESS', 'COMPLETED']), _negated=True), ('started_at__isnull', False), _connector='OR'), name='audit_running_has_started_at'),
        ),
    ]
