# Generated by Django 5.0.14 on 2026-10-02 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_orgevent'),
        ('quality', '0003_internal_audits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityevent',
            name='kind',
            field=models.CharField(choices=[('nc_reported', 'عدم\u200cانطباق ثبت شد'), ('nc_edited', 'عدم\u200cانطباق ویرایش شد'), ('nc_accepted', 'عدم\u200cانطباق پذیرفته شد'), ('nc_rejected', 'عدم\u200cانطباق رد شد'), ('nc_closed', 'عدم\u200cانطباق بسته شد'), ('nc_reopened', 'عدم\u200cانطباق بازگشایی شد'), ('action_added', 'اقدام اصلاحی افزوده شد'), ('action_edited', 'اقدام اصلاحی ویرایش شد'), ('action_assigned', 'اقدام اصلاحی واگذار شد'), ('action_status_changed', 'وضعیت اقدام تغییر کرد'), ('action_due_changed', 'مهلت اقدام تغییر کرد'), ('action_verified', 'اقدام تایید شد'), ('action_verification_failed', 'تایید اقدام ناموفق بود'), ('action_cancelled', 'اقدام لغو شد'), ('audit_planned', 'ممیزی برنامه\u200cریزی شد'), ('audit_edited', 'ممیزی ویرایش شد'), ('audit_auditor_changed', 'ممیز اصلی تغییر کرد'), ('audit_started', 'ممیزی آغاز شد'), ('audit_completed', 'ممیزی انجام شد'), ('audit_cancelled', 'ممیزی لغو شد'), ('finding_raised', 'یافتهٔ ممیزی ثبت شد'), ('risk_created', 'ریسک ثبت شد'), ('risk_edited', 'ریسک ویرایش شد'), ('risk_assessed', 'ارزیابی ریسک تغییر کرد'), ('risk_status_changed', 'وضعیت ریسک تغییر کرد')], max_length=32),
        ),
        migrations.CreateModel(
            name='RiskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('likelihood', models.PositiveSmallIntegerField()),
                ('impact', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('IDENTIFIED', 'شناسایی\u200cشده'), ('MITIGATING', 'در حال کاهش'), ('ACCEPTED', 'پذیرفته\u200cشده'), ('CLOSED', 'بسته\u200cشده')], default='IDENTIFIED', max_length=12)),
                ('mitigation_plan', models.TextField(blank=True)),
                ('review_on', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_risks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
                ('owner_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='organization.orgnode')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='qualityevent',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quality.riskitem'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['risk', 'created_at'], name='qevent_risk_time_idx'),
        ),
        migrations.AddIndex(
            model_name='riskitem',
            index=models.Index(fields=['status', 'owner_node'], name='risk_status_node_idx'),
        ),
        migrations.AddIndex(
            model_name='riskitem',
            index=models.Index(fields=['owner', 'status'], name='risk_owner_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='riskitem',
            constraint=models.CheckConstraint(check=models.Q(('likelihood__gte', 1), ('likelihood__lte', 5), ('impact__gte', 1), ('impact__lte', 5)), name='risk_scales_between_1_and_5'),
        ),
    ]
