# Generated by Django 5.0.14 on 2026-09-21 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_key', models.CharField(max_length=255)),
                ('goal', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'در حال اجرا'), ('ON_HOLD', 'متوقف'), ('DONE', 'پایان\u200cیافته'), ('CANCELLED', 'لغو شده')], default='ACTIVE', max_length=16)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='organization.orgnode')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('project_created', 'پروژه ایجاد شد'), ('project_status_changed', 'وضعیت پروژه تغییر کرد'), ('project_archived', 'پروژه بایگانی شد'), ('project_unarchived', 'پروژه از بایگانی خارج شد'), ('member_added', 'عضو افزوده شد'), ('guest_invited', 'مهمان دعوت شد'), ('member_role_changed', 'نقش عضو تغییر کرد'), ('member_removed', 'عضو حذف شد'), ('objective_added', 'ریزهدف افزوده شد'), ('objective_assigned', 'ریزهدف واگذار شد'), ('objective_status_changed', 'وضعیت ریزهدف تغییر کرد'), ('objective_due_changed', 'مهلت ریزهدف تغییر کرد'), ('objective_removed', 'ریزهدف حذف شد'), ('comment_added', 'یادداشت افزوده شد'), ('document_linked', 'مستند پیوست شد')], max_length=32)),
                ('actor_name', models.CharField(max_length=255)),
                ('actor_title', models.CharField(blank=True, max_length=255)),
                ('subject_title', models.CharField(blank=True, max_length=255)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(blank=True, max_length=16)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.project')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('MANAGER', 'مدیر پروژه'), ('MEMBER', 'عضو')], default='MEMBER', max_length=8)),
                ('is_guest', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['section', 'status'], name='project_section_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('section', 'name_key'), name='uniq_project_name_per_section'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('starts_on__isnull', True), ('due_on__isnull', True), ('due_on__gte', models.F('starts_on')), _connector='OR'), name='project_due_not_before_start'),
        ),
        migrations.AddIndex(
            model_name='projectevent',
            index=models.Index(fields=['project', 'created_at'], name='projectevent_project_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='uniq_project_member'),
        ),
    ]
