# Generated by Django 5.0.14 on 2026-09-21 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_on', models.DateField()),
                ('status', models.CharField(choices=[('TODO', 'انجام نشده'), ('IN_PROGRESS', 'در حال انجام'), ('BLOCKED', 'متوقف'), ('DONE', 'انجام شد'), ('CANCELLED', 'لغو شد')], default='TODO', max_length=16)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objectives', to='projects.projectmember')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='projects.project')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='projectevent',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='projects.objective'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['project', 'position'], name='objective_project_position_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['assignee', 'status'], name='objective_assignee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['status', 'due_on'], name='objective_status_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='objective',
            constraint=models.CheckConstraint(check=models.Q(('weight__gte', 1)), name='objective_weight_positive'),
        ),
    ]
