# Generated by Django 5.0.14 on 2026-09-25 18:32, then hand-edited to insert the data copy
# (RunPython) between creating the table and dropping the old assignee column — see
# docs/12-phase-10-adr.md section D.

import django.db.models.deletion
from django.db import migrations, models


def copy_assignee_to_assignees(apps, schema_editor):
    """One ObjectiveAssignee row per existing Objective.assignee, while the column still exists."""
    Objective = apps.get_model("projects", "Objective")
    ObjectiveAssignee = apps.get_model("projects", "ObjectiveAssignee")
    ObjectiveAssignee.objects.bulk_create(
        ObjectiveAssignee(objective_id=objective_id, member_id=assignee_id)
        for objective_id, assignee_id in Objective.objects.values_list("id", "assignee_id")
        if assignee_id is not None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_comments_and_document_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='objectiveassignee',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objective_assignments', to='projects.projectmember'),
        ),
        migrations.AddField(
            model_name='objectiveassignee',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='projects.objective'),
        ),
        migrations.AddConstraint(
            model_name='objectiveassignee',
            constraint=models.UniqueConstraint(fields=('objective', 'member'), name='uniq_objective_assignee'),
        ),
        migrations.RunPython(copy_assignee_to_assignees, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='objective',
            name='objective_assignee_status_idx',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='assignee',
        ),
    ]
