# Generated by Django 5.0.14 on 2026-09-25 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_objective_assignees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectevent',
            name='kind',
            field=models.CharField(choices=[('project_created', 'پروژه ایجاد شد'), ('project_status_changed', 'وضعیت پروژه تغییر کرد'), ('project_archived', 'پروژه بایگانی شد'), ('project_unarchived', 'پروژه از بایگانی خارج شد'), ('member_added', 'عضو افزوده شد'), ('guest_invited', 'مهمان دعوت شد'), ('member_role_changed', 'نقش عضو تغییر کرد'), ('member_removed', 'عضو حذف شد'), ('objective_added', 'ریزهدف افزوده شد'), ('objective_assigned', 'ریزهدف واگذار شد'), ('objective_status_changed', 'وضعیت ریزهدف تغییر کرد'), ('objective_due_changed', 'مهلت ریزهدف تغییر کرد'), ('objective_removed', 'ریزهدف حذف شد'), ('objective_update_added', 'گزارش پیشرفت ثبت شد'), ('comment_added', 'یادداشت افزوده شد'), ('comment_removed', 'یادداشت حذف شد'), ('document_linked', 'مستند پیوست شد'), ('document_unlinked', 'پیوند مستند حذف شد')], max_length=32),
        ),
        migrations.CreateModel(
            name='ObjectiveUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=255)),
                ('author_title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.objective')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['objective', 'created_at'], name='obj_update_obj_time_idx'), models.Index(fields=['objective', 'author'], name='obj_update_obj_author_idx')],
            },
        ),
    ]
