# Generated by Django 5.0.14 on 2026-09-26 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_objective_updates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectevent',
            name='kind',
            field=models.CharField(choices=[('project_created', 'پروژه ایجاد شد'), ('project_status_changed', 'وضعیت پروژه تغییر کرد'), ('project_archived', 'پروژه بایگانی شد'), ('project_unarchived', 'پروژه از بایگانی خارج شد'), ('member_added', 'عضو افزوده شد'), ('guest_invited', 'مهمان دعوت شد'), ('member_role_changed', 'نقش عضو تغییر کرد'), ('member_removed', 'عضو حذف شد'), ('objective_added', 'ریزهدف افزوده شد'), ('objective_assigned', 'ریزهدف واگذار شد'), ('objective_status_changed', 'وضعیت ریزهدف تغییر کرد'), ('objective_due_changed', 'مهلت ریزهدف تغییر کرد'), ('objective_removed', 'ریزهدف حذف شد'), ('objective_update_added', 'گزارش پیشرفت ثبت شد'), ('comment_added', 'یادداشت افزوده شد'), ('comment_removed', 'یادداشت حذف شد'), ('document_linked', 'مستند پیوست شد'), ('document_unlinked', 'پیوند مستند حذف شد'), ('meeting_scheduled', 'جلسه تعیین شد'), ('meeting_changed', 'جلسه تغییر کرد'), ('meeting_cancelled', 'جلسه لغو شد')], max_length=32),
        ),
        migrations.CreateModel(
            name='ProjectMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('held_on', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='projects.project')),
            ],
            options={
                'ordering': ['-held_on', models.OrderBy(models.F('start_time'), descending=True, nulls_last=True), '-id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_invitations', to='projects.projectmember')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='projects.projectmeeting')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='projectmeeting',
            index=models.Index(fields=['project', 'held_on'], name='meeting_project_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingattendee',
            constraint=models.UniqueConstraint(fields=('meeting', 'member'), name='uniq_meeting_attendee'),
        ),
    ]
