# Generated by Django 5.0.14 on 2026-10-01 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('document_awaiting_confirmation', 'مستند منتظر تایید شماست'), ('document_awaiting_approval', 'مستند منتظر تصویب شماست'), ('document_approved', 'مستند تصویب و ابلاغ شد'), ('document_returned', 'مستند مرجوع شد'), ('document_stalled', 'مستند مدتی است منتظر مانده'), ('membership_added', 'عضویت جدید در ساختار سازمانی'), ('membership_removed', 'پایان عضویت در ساختار سازمانی'), ('lead_assigned', 'مسئولیت یک گره به شما واگذار شد'), ('objective_due_soon', 'ریزهدف نزدیک به مهلت است'), ('objective_overdue', 'ریزهدف از مهلت گذشته است')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=255)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notif_recipient_unread_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('recipient', 'dedupe_key'), name='uniq_notif_recipient_dedupe'),
        ),
    ]
