# Generated by Django 5.0.14 on 2026-10-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('document_awaiting_confirmation', 'مستند منتظر تایید شماست'), ('document_awaiting_approval', 'مستند منتظر تصویب شماست'), ('document_approved', 'مستند تصویب و ابلاغ شد'), ('document_returned', 'مستند مرجوع شد'), ('document_stalled', 'مستند مدتی است منتظر مانده'), ('membership_added', 'عضویت جدید در ساختار سازمانی'), ('membership_removed', 'پایان عضویت در ساختار سازمانی'), ('lead_assigned', 'مسئولیت یک گره به شما واگذار شد'), ('delegation_received', 'جانشینی موقت یک مسئول به شما سپرده شد'), ('nc_reported', 'عدم\u200cانطباق جدیدی ثبت شد'), ('nc_accepted', 'عدم\u200cانطباق شما پذیرفته شد'), ('nc_rejected', 'عدم\u200cانطباق شما رد شد'), ('objective_due_soon', 'ریزهدف نزدیک به مهلت است'), ('objective_overdue', 'ریزهدف از مهلت گذشته است')], max_length=40),
        ),
    ]
