# Generated by Django 5.0.14 on 2026-10-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_risk_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('document_awaiting_confirmation', 'مستند منتظر تایید شماست'), ('document_awaiting_approval', 'مستند منتظر تصویب شماست'), ('document_approved', 'مستند تصویب و ابلاغ شد'), ('document_returned', 'مستند مرجوع شد'), ('document_stalled', 'مستند مدتی است منتظر مانده'), ('membership_added', 'عضویت جدید در ساختار سازمانی'), ('membership_removed', 'پایان عضویت در ساختار سازمانی'), ('lead_assigned', 'مسئولیت یک گره به شما واگذار شد'), ('delegation_received', 'جانشینی موقت یک مسئول به شما سپرده شد'), ('nc_reported', 'عدم\u200cانطباق جدیدی ثبت شد'), ('nc_accepted', 'عدم\u200cانطباق شما پذیرفته شد'), ('nc_rejected', 'عدم\u200cانطباق شما رد شد'), ('nc_closed', 'عدم\u200cانطباق بسته شد'), ('capa_assigned', 'اقدام اصلاحی به شما واگذار شد'), ('capa_ready_to_verify', 'اقدام اصلاحی منتظر تایید شماست'), ('capa_verified', 'اقدام اصلاحی شما تایید شد'), ('capa_verification_failed', 'تایید اقدام اصلاحی شما ناموفق بود'), ('capa_cancelled', 'اقدام اصلاحی شما لغو شد'), ('capa_due_soon', 'اقدام اصلاحی نزدیک به مهلت است'), ('capa_overdue', 'اقدام اصلاحی از مهلت گذشته است'), ('audit_planned', 'ممیزی داخلی برنامه\u200cریزی شد'), ('audit_cancelled', 'ممیزی داخلی لغو شد'), ('risk_assigned', 'ریسکی به شما سپرده شد'), ('risk_review_due', 'زمان بازنگری یک ریسک رسیده است'), ('leave_requested', 'درخواست مرخصی منتظر تصمیم شماست'), ('leave_approved', 'درخواست مرخصی شما تایید شد'), ('leave_rejected', 'درخواست مرخصی شما رد شد'), ('leave_cancelled', 'مرخصی تاییدشده لغو شد'), ('objective_due_soon', 'ریزهدف نزدیک به مهلت است'), ('objective_overdue', 'ریزهدف از مهلت گذشته است')], max_length=40),
        ),
    ]
