# Generated by Django 5.0.14 on 2026-09-19 22:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_document_content_version_document_footnote1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('official', 'رسمی'), ('preview', 'پیش\u200cنمایش')], max_length=16)),
                ('status', models.CharField(choices=[('building', 'در حال ساخت'), ('ready', 'آماده'), ('failed', 'ناموفق')], default='building', max_length=16)),
                ('token', models.CharField(default='', max_length=32)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('built_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_builds', to='documents.document')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='pdfbuild',
            constraint=models.UniqueConstraint(fields=('document', 'kind'), name='uniq_pdf_build_per_kind'),
        ),
    ]
