# Generated by Django 5.0.14 on 2026-09-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.CharField(choices=[('L1', 'لول ۱'), ('L2', 'لول ۲'), ('L3', 'لول ۳')], max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_roll',
            field=models.CharField(choices=[('EMPLOYER', 'کارفرمایی'), ('HEADQUARTERS', 'ستادی'), ('GUILD', 'صفی')], max_length=16),
        ),
    ]
