# Generated by Django 5.0.14 on 2026-09-21 14:06

import apps.organization.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('COMPANY', 'شرکت'), ('DOMAIN', 'حوزه'), ('UNIT', 'واحد'), ('SECTION', 'بخش')], max_length=8)),
                ('parent_kind', models.CharField(blank=True, choices=[('COMPANY', 'شرکت'), ('DOMAIN', 'حوزه'), ('UNIT', 'واحد'), ('SECTION', 'بخش')], max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('name_key', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('depth', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.orgnode')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('national_id', models.CharField(blank=True, max_length=32)),
                ('logo', models.ImageField(blank=True, upload_to=apps.organization.models.company_logo_upload_to)),
                ('setup_step', models.CharField(choices=[('COMPANY', 'شرکت'), ('DOMAINS', 'حوزه\u200cها'), ('UNITS', 'واحدها'), ('SECTIONS', 'بخش\u200cها'), ('PEOPLE', 'افراد'), ('DONE', 'پایان')], default='COMPANY', max_length=16)),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('root', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company', to='organization.orgnode')),
            ],
        ),
        migrations.AddIndex(
            model_name='orgnode',
            index=models.Index(fields=['path'], name='org_node_path_idx'),
        ),
        migrations.AddIndex(
            model_name='orgnode',
            index=models.Index(fields=['kind', 'is_active'], name='org_node_kind_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgnode',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'COMPANY')), fields=('kind',), name='uniq_company_root_node'),
        ),
        migrations.AddConstraint(
            model_name='orgnode',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind', 'COMPANY'), ('parent__isnull', True)), models.Q(('parent__isnull', False), models.Q(('kind', 'COMPANY'), _negated=True)), _connector='OR'), name='org_node_root_iff_company'),
        ),
        migrations.AddConstraint(
            model_name='orgnode',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind', 'COMPANY'), ('parent_kind__in', [''])), models.Q(('kind', 'DOMAIN'), ('parent_kind__in', ['COMPANY'])), models.Q(('kind', 'UNIT'), ('parent_kind__in', ['COMPANY', 'DOMAIN'])), models.Q(('kind', 'SECTION'), ('parent_kind__in', ['UNIT'])), _connector='OR'), name='org_node_parent_kind_allowed'),
        ),
        migrations.AddConstraint(
            model_name='orgnode',
            constraint=models.UniqueConstraint(fields=('parent', 'name_key'), name='uniq_org_node_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(check=models.Q(('pk', 1)), name='company_is_singleton'),
        ),
    ]
