# Generated by Django 5.0.14 on 2026-09-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='doc_footnote1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='doc_footnote2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='form_show_letter_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='form_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
