# Generated by Django 5.0.14 on 2026-10-02 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_document_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='organization.orgnode')),
            ],
            options={
                'ordering': ['-starts_on', '-id'],
                'indexes': [models.Index(fields=['node', 'starts_on', 'ends_on'], name='delegation_node_window_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='delegation',
            constraint=models.CheckConstraint(check=models.Q(('ends_on__gte', models.F('starts_on'))), name='delegation_ends_not_before_start'),
        ),
    ]
