# Generated by Django 5.0.14 on 2026-10-02 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_delegation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('node_created', 'گره ایجاد شد'), ('node_renamed', 'نام گره تغییر کرد'), ('node_moved', 'گره جابه\u200cجا شد'), ('node_archived', 'گره بایگانی شد'), ('node_unarchived', 'گره از بایگانی خارج شد'), ('node_deleted', 'گره حذف شد'), ('member_added', 'عضو افزوده شد'), ('member_removed', 'عضو حذف شد'), ('lead_granted', 'مسئولیت واگذار شد'), ('lead_revoked', 'مسئولیت برداشته شد'), ('delegation_created', 'جانشین موقت تعیین شد'), ('delegation_ended', 'جانشینی موقت پایان یافت')], max_length=24)),
                ('actor_name', models.CharField(max_length=255)),
                ('actor_title', models.CharField(blank=True, max_length=255)),
                ('node_name', models.CharField(blank=True, max_length=255)),
                ('subject_name', models.CharField(blank=True, max_length=255)),
                ('from_value', models.CharField(blank=True, max_length=255)),
                ('to_value', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='organization.orgnode')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['node', 'created_at'], name='orgevent_node_time_idx')],
            },
        ),
    ]
