# Generated by Django 5.0.14 on 2026-09-20 12:41

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_content_version_document_footnote1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signoff',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='signature',
            field=models.ImageField(blank=True, upload_to=apps.documents.models.signature_upload_to),
        ),
        migrations.CreateModel(
            name='DocumentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('submitted', 'ارسال برای تایید'), ('confirmed', 'تایید شد'), ('approved', 'تصویب شد'), ('returned', 'مرجوع شد'), ('superseded', 'منسوخ شد (جایگزین شد)')], max_length=16)),
                ('from_status', models.CharField(choices=[('DRAFT', 'پیش نویس'), ('AWAITING_CONFIRMATION', 'در انتظار تأیید'), ('AWAITING_APPROVAL', 'در انتظار تصویب'), ('UNDER_CONTROL', 'تحت کنترل'), ('OBSOLETE', 'منسوخ شده')], max_length=24)),
                ('to_status', models.CharField(choices=[('DRAFT', 'پیش نویس'), ('AWAITING_CONFIRMATION', 'در انتظار تأیید'), ('AWAITING_APPROVAL', 'در انتظار تصویب'), ('UNDER_CONTROL', 'تحت کنترل'), ('OBSOLETE', 'منسوخ شده')], max_length=24)),
                ('actor_name', models.CharField(max_length=255)),
                ('actor_title', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='documents.document')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['document', 'created_at'], name='documents_d_documen_98fd46_idx')],
            },
        ),
    ]
