# Generated by Django 5.0.14 on 2026-09-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_signoff_signed_by_alter_signoff_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentevent',
            name='kind',
            field=models.CharField(choices=[('submitted', 'ارسال برای تایید'), ('confirmed', 'تایید شد'), ('approved', 'تصویب شد'), ('returned', 'مرجوع شد'), ('superseded', 'منسوخ شد (جایگزین شد)'), ('imported', 'وارد شده از نسخهٔ ۱')], max_length=16),
        ),
    ]
