# Generated by Django 5.0.14 on 2026-09-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_documentevent_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='body_kind',
            field=models.CharField(choices=[('blocks', 'متن'), ('form', 'فرم')], default='blocks', max_length=8),
        ),
        migrations.AddField(
            model_name='document',
            name='form_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('Short Explanation', 'تشریحی کوتاه'), ('Long Explanation', 'تشریحی بلند'), ('Responsibilities', 'مسئولیت ها'), ('Changes Table', 'جدول تغییرات'), ('Attachment', 'ضمائم'), ('Form Element', 'جزء فرم')], max_length=24),
        ),
    ]
