# Generated by Django 5.0.14 on 2026-09-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_empty_form_drafts_become_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='show_company_name',
            field=models.BooleanField(default=False),
        ),
    ]
