# Generated by Django 5.0.14 on 2026-09-25 19:08

import apps.chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=255, upload_to=apps.chat.models.message_attachment_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('PICTURE', 'تصویر'), ('DOCUMENT', 'فایل'), ('VIDEO', 'ویدیو')], max_length=16)),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
