# Generated by Django 5.0.14 on 2026-10-08 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0005_orgevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_name', models.CharField(blank=True, max_length=255)),
                ('leave_type', models.CharField(choices=[('ANNUAL', 'استحقاقی'), ('SICK', 'استعلاجی'), ('UNPAID', 'بدون حقوق')], default='ANNUAL', max_length=8)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'منتظر تایید'), ('APPROVED', 'تایید شد'), ('REJECTED', 'رد شد'), ('CANCELLED', 'لغو شد')], default='PENDING', max_length=10)),
                ('decided_by_name', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='organization.orgnode')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_on', '-id'],
                'indexes': [models.Index(fields=['status', 'node'], name='leave_status_node_idx'), models.Index(fields=['requester', 'starts_on'], name='leave_requester_start_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(check=models.Q(('ends_on__gte', models.F('starts_on'))), name='leave_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status__in', ['APPROVED', 'REJECTED']), _negated=True), ('decided_at__isnull', False), _connector='OR'), name='leave_decided_has_decided_at'),
        ),
    ]
