# Generated by Django 5.0.14 on 2026-09-19 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('group', models.CharField(choices=[('POSTER', 'پوستر'), ('PROCEDURE', 'روش اجرایی'), ('INSTRUCTION', 'دستورالعمل'), ('FORM', 'فرم')], max_length=16, primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('INSIDE', 'داخل سازمانی'), ('OUTSIDE', 'برون سازمانی')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('POSTER', 'پوستر'), ('PROCEDURE', 'روش اجرایی'), ('INSTRUCTION', 'دستورالعمل'), ('FORM', 'فرم')], max_length=16)),
                ('number', models.PositiveIntegerField()),
                ('revision', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'پیش نویس'), ('AWAITING_CONFIRMATION', 'در انتظار تأیید'), ('AWAITING_APPROVAL', 'در انتظار تصویب'), ('UNDER_CONTROL', 'تحت کنترل'), ('OBSOLETE', 'منسوخ شده')], default='DRAFT', max_length=24)),
                ('content_saved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('previous_revision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_revision', to='documents.document')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SignOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('creater', 'تدوین کننده'), ('confirmer', 'تایید کننده'), ('approver', 'تصویب کننده')], max_length=16)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('signature', models.ImageField(blank=True, upload_to='signatures/')),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signoffs', to='documents.document')),
            ],
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['group', 'title'], name='documents_d_group_cdfc4c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('group', 'number', 'revision'), name='uniq_document_code_revision'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('revision', 1)), fields=('group', 'title'), name='uniq_document_title_per_group'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(check=models.Q(('revision__gte', 1), ('revision__lte', 99)), name='document_revision_in_range'),
        ),
        migrations.AddConstraint(
            model_name='signoff',
            constraint=models.UniqueConstraint(fields=('document', 'role'), name='uniq_signoff_role_per_document'),
        ),
    ]
