# Generated by Django 5.0.14 on 2026-09-19 17:10

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='footnote1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='footnote2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='logo',
            field=models.ImageField(blank=True, upload_to=apps.documents.models.logo_upload_to),
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=255, upload_to=apps.documents.models.document_file_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('PICTURE', 'تصویر'), ('DOCUMENT', 'فایل'), ('VIDEO', 'ویدیو')], max_length=16)),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.document')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('Short Explanation', 'تشریحی کوتاه'), ('Long Explanation', 'تشریحی بلند'), ('Responsibilities', 'مسئولیت ها'), ('Changes Table', 'جدول تغییرات'), ('Attachment', 'ضمائم')], max_length=24)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='documents.document')),
                ('files', models.ManyToManyField(blank=True, related_name='sections', to='documents.documentfile')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResponsibilityRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('role', models.CharField(blank=True, choices=[('responder', 'پاسخگو'), ('receiver', 'پاسخ\u200cخواه'), ('cash_account', 'حسابکش'), ('supervisor', 'ناظر')], max_length=16)),
                ('post', models.CharField(blank=True, max_length=255)),
                ('supervisor', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibility_rows', to='documents.section')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChangeTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_rows', to='documents.section')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttachmentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('caption', models.CharField(max_length=255)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referenced_by', to='documents.document')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_items', to='documents.section')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentfile',
            constraint=models.UniqueConstraint(fields=('document', 'sha256'), name='uniq_document_file_content'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['document', 'position'], name='documents_s_documen_85c48c_idx'),
        ),
        migrations.AddConstraint(
            model_name='responsibilityrow',
            constraint=models.UniqueConstraint(condition=models.Q(('role', ''), _negated=True), fields=('section', 'role'), name='uniq_responsibility_role_per_section'),
        ),
    ]
